name: Production Deployment

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment without tag'
        required: false
        type: boolean
        default: false

concurrency:
  group: production-deploy
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/cdk-test.yml

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
          role-session-name: GitHubActions-Production

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap CDK (if needed)
        run: |
          if ! aws cloudformation describe-stacks --stack-name CDKToolkit 2>/dev/null; then
            npx cdk bootstrap aws://${{ secrets.PROD_AWS_ACCOUNT_ID }}/${{ secrets.PROD_AWS_REGION }} --context envType=prod
          fi

      - name: Validate Production Change Set
        run: |
          # Check if override is requested
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == *"[force-deploy]"* ]]; then
            echo "🚨 Force deploy detected - skipping change set validation"
          else
            # Use stack name from tag or default
            STACK_NAME="TAK-Prod-BaseInfra"
            ./scripts/github/validate-changeset.sh $STACK_NAME
          fi

      - name: Deploy Production
        run: npm run deploy:prod -- --require-approval never